ports:
  - port: 8000
    onOpen: open-preview

tasks:
  - init: |
      brew update
      brew install just
    command: |
      just initial-setup
# vscode:
#   extensions:
#     - ms-python.python
